### ISSUE TITLE
Don't close doors when modifying drawing

### ISSUE THREAD

**Issue by dtgay** [mcglincy/dungeondraw-foundry-vtt#88] opened 2022-04-01 01:02 UTC
Seems like doors close (or reset) when the DM draws new content. A fairly big annoyance to players that prevents me from using this module to its full potential -- I'd _love_ to be able to draw the map as we go, like the Old Days:tm:.

Any way to work around this, or ideas for fixing it?

_And thanks for an incredible module! This is just about exactly what I was looking for._

**Comment by mcglincy** [comment] 2022-04-01 01:11
Just to verify I am understanding the bug: you draw some dungeon area, you draw a door, you open the door, you draw some more dungeon area, and now the previously-open door is closed?

**Comment by mcglincy** [comment] 2022-04-22 22:02
Confirmed the unwanted behavior and why it's happening in code, which is because the scene's wall documents (including doors) are recreated for each dungeon state change, which thus drops a previously-opened door and replaces it with a new, closed door.

DD's makeWalls() routine needs to be smarter, and should avoid unnecessarily recreating doors each state change.

**Comment by mcglincy** [comment] 2022-04-23 18:29
Fixed in 0.23.1.

**Closed by mcglincy** 2022-04-23 18:29 UTC
